apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-cont
          image: abdu14/spring-app
          ports:
            - containerPort: 8080
              name: my-port
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name:
                  value:
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - name: app-svc-port
      port: 8090
      protocol: TCP
      targetPort: my-port
