apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-cont
          image: abdu14/spring-app
          resources:
            limits:
              memory: "500mi"
              cpu: "500mi"
          ports:
            - name: my-port
              containerPort: 8080
          env:
            - name: HOST
              # value: mysql-svc
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysql_host
            - name: PORT
#              value: "3307"
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysql_port
            - name: DB_NAME
#              value: testdb
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysql_database
            - name: DB_USER
#              value: testu
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-user
            - name: DB_PASSWORD
#              value: testp
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-pass
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  ports:
    - name: app-svc-port
      port: 8090
      protocol: TCP
      targetPort: my-port
  type: NodePort
