apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-cont
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: mysql-port
          env:
            - name: MYSQL_ROOT_PASSWORD
#              value: root
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: root-pass
            - name: MYSQL_USER
#              value: testu
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
#              value: testp
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-pass
            - name: MYSQL_DATABASE
#              value: testdb
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mysql-database
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc-1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-app
  ports:
    - port: 3307
      protocol: TCP
      targetPort: mysql-port
