spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://${HOST:database-1-abdulkerimahmed14-df47.a.aivencloud.com}:${PORT:16919}/${DB_NAME:defaultdb}
    username: ${DB_USER:avnadmin}
    password: ${DB_PASSWORD:AVNS_vxGVT7IwDwO66-xVHkv}
  jpa:
    hibernate:
      ddl-auto: create